export {default as HomePage} from './home/Home'
export {default as AboutPage} from './about/About'
export {default as RoomPage} from './room/Room'
export {default as DevicePage} from './device/Device'
export {default as NotFoundPage} from './notFound/NotFound'
export {default as SensorDataPage} from './sensor/SensorData'